CREATE DATABASE form_database;

USE form_database;

CREATE TABLE form_data(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL,
	email VARCHAR(30) CHARACTER SET UTF8MB4 NOT NULL,
    plate VARCHAR(20) CHARACTER SET UTF8MB4 NOT NULL,
    juice BOOLEAN,
    pepper VARCHAR(25) CHARACTER SET UTF8MB4
);

SELECT * FROM form_data;